class DominosTester{
public static void main(String args[]){
String foodName = "Garlicbread";
double priceOfFoodName=Dominos.search(foodName);
System.out.println("Price of foodName is " +priceOfFoodName);
String foodName1 = "OnionPizza";
double priceOfFoodName1=Dominos.search(foodName1);
System.out.println("Price of foodName is " +priceOfFoodName1);
String foodName2 = "Peppypaneer";
double priceOfFoodName2=Dominos.search(foodName2);
System.out.println("Price of foodName is " +priceOfFoodName2);
String foodName3 = "Margherita";
double priceOfFoodName3=Dominos.search(foodName3);
System.out.println("Price of foodName is " +priceOfFoodName3);
String foodName4 = "Vegloaded";
double priceOfFoodName4=Dominos.search(foodName4);
System.out.println("Price of foodName is " +priceOfFoodName4);
String foodName5 = "CheesyPizza";
double priceOfFoodName5=Dominos.search(foodName5);
System.out.println("Price of foodName is " +priceOfFoodName5);
String foodName6 = "VegCheesy";
double priceOfFoodName6=Dominos.search(foodName6);
System.out.println("Price of foodName is " +priceOfFoodName6);
String foodName7 = "VegextraVaganza";
double priceOfFoodName7=Dominos.search(foodName7);
System.out.println("Price of foodName is " +priceOfFoodName7);
String foodName8 = "VegParadies";
double priceOfFoodName8=Dominos.search(foodName8);
System.out.println("Price of foodName is " +priceOfFoodName8);
String foodName9 = "CornPizza";
double priceOfFoodName9=Dominos.search(foodName9);
System.out.println("Price of foodName is " +priceOfFoodName9);
String foodName10 = "PaneerPizza";
double priceOfFoodName10=Dominos.search(foodName10);
System.out.println("Price of foodName is " +priceOfFoodName10);
String foodName11 = "PizzaMania";
double priceOfFoodName11=Dominos.search(foodName11);
System.out.println("Price of foodName is " +priceOfFoodName11);
String foodName12 = "VegPizza";
double priceOfFoodName12=Dominos.search(foodName12);
System.out.println("Price of foodName is " +priceOfFoodName12);
String foodName13 = "GourmetPizza";
double priceOfFoodName13=Dominos.search(foodName13);
System.out.println("Price of foodName is " +priceOfFoodName13);
String foodName14 = "PaneerTikkaPizza";
double priceOfFoodName14=Dominos.search(foodName14);
System.out.println("Price of foodName is " +priceOfFoodName14);
String foodName15 = "CheesyDip";
double priceOfFoodName15=Dominos.search(foodName15);
System.out.println("Price of foodName is " +priceOfFoodName15);
String foodName16 = "CheesyJalapeno";
double priceOfFoodName16=Dominos.search(foodName16);
System.out.println("Price of foodName is " +priceOfFoodName16);
String foodName17 = "Moroccanpasta";
double priceOfFoodName17=Dominos.search(foodName17);
System.out.println("Price of foodName is " +priceOfFoodName17);
String foodName18 = "PapperBBQChicken";
double priceOfFoodName18=Dominos.search(foodName18);
System.out.println("Price of foodName is " +priceOfFoodName18);
String foodName19 = "ChocoLavaCake";
double priceOfFoodName19=Dominos.search(foodName19);
System.out.println("Price of foodName is " +priceOfFoodName19);
String foodName20 = "ChickenPepperoni";
double priceOfFoodName20=Dominos.search(foodName20);
System.out.println("Price of foodName is " +priceOfFoodName20);
}
}