class KFCTester{
public static void main(String args[]){
String foodName = "Bucketchicken";
double priceOfFoodName=KFC.search(foodName);
System.out.println("Price of foodName is " +priceOfFoodName);
String foodName1 = "StripsBucket";
double priceOfFoodName1=KFC.search(foodName1);
System.out.println("Price of foodName is " +priceOfFoodName1);
String foodName2 = "Legpiece";
double priceOfFoodName2=KFC.search(foodName2);
System.out.println("Price of foodName is " +priceOfFoodName2);
String foodName3 = "CheeseCorn";
double priceOfFoodName3=KFC.search(foodName3);
System.out.println("Price of foodName is " +priceOfFoodName3);
String foodName4 = "DipsBucket";
double priceOfFoodName4=KFC.search(foodName4);
System.out.println("Price of foodName is " +priceOfFoodName4);
String foodName5 = "HotChicken";
double priceOfFoodName5=KFC.search(foodName5);
System.out.println("Price of foodName is " +priceOfFoodName5);
String foodName6 = "KrisperBurger";
double priceOfFoodName6=KFC.search(foodName6);
System.out.println("Price of foodName is " +priceOfFoodName6);
String foodName7 = "ZingerBurger";
double priceOfFoodName7=KFC.search(foodName7);
System.out.println("Price of foodName is " +priceOfFoodName7);
String foodName8 = "ChickenStrips";
double priceOfFoodName8=KFC.search(foodName8);
System.out.println("Price of foodName is " +priceOfFoodName8);
String foodName9 = "HotWings";
double priceOfFoodName9=KFC.search(foodName9);
System.out.println("Price of foodName is " +priceOfFoodName9);
String foodName10 = "PopCornRice";
double priceOfFoodName10=KFC.search(foodName10);
System.out.println("Price of foodName is " +priceOfFoodName10);
String foodName11 = "ChickenRice";
double priceOfFoodName11=KFC.search(foodName11);
System.out.println("Price of foodName is " +priceOfFoodName11);
String foodName12 = "VegRice";
double priceOfFoodName12=KFC.search(foodName12);
System.out.println("Price of foodName is " +priceOfFoodName12);
String foodName13 = "RiceDuo";
double priceOfFoodName13=KFC.search(foodName13);
System.out.println("Price of foodName is " +priceOfFoodName13);
String foodName14 = "PopCorn";
double priceOfFoodName14=KFC.search(foodName14);
System.out.println("Price of foodName is " +priceOfFoodName14);
String foodName15 = "ChickenRoll";
double priceOfFoodName15=KFC.search(foodName15);
System.out.println("Price of foodName is " +priceOfFoodName15);
String foodName16 = "TandooriZinger";
double priceOfFoodName16=KFC.search(foodName16);
System.out.println("Price of foodName is " +priceOfFoodName16);
String foodName17 = "VegRoll";
double priceOfFoodName17=KFC.search(foodName17);
System.out.println("Price of foodName is " +priceOfFoodName17);
String foodName18 = "LargeFries";
double priceOfFoodName18=KFC.search(foodName18);
System.out.println("Price of foodName is " +priceOfFoodName18);
String foodName19 = "Vegpatty";
double priceOfFoodName19=KFC.search(foodName19);
System.out.println("Price of foodName is " +priceOfFoodName19);
String foodName20 = "Dips";
double priceOfFoodName20=KFC.search(foodName20);
System.out.println("Price of foodName is " +priceOfFoodName20);
}
}