class SwiggyTester{
public static void main(String args[]){
String foodName = "FriedRice";
double priceOfFoodName=Swiggy.search(foodName);
System.out.println("Price of foodName is " +priceOfFoodName);
String foodName1 = "VadaPav";
double priceOfFoodName1=Swiggy.search(foodName1);
System.out.println("Price of foodName is " +priceOfFoodName1);
String foodName2 = "CheeseGarlic";
double priceOfFoodName2=Swiggy.search(foodName2);
System.out.println("Price of foodName is " +priceOfFoodName2);
String foodName3 = "CheeseCorn";
double priceOfFoodName3=Swiggy.search(foodName3);
System.out.println("Price of foodName is " +priceOfFoodName3);
String foodName4 = "PavBajji";
double priceOfFoodName4=Swiggy.search(foodName4);
System.out.println("Price of foodName is " +priceOfFoodName4);
String foodName5 = "PaneerTikka";
double priceOfFoodName5=Swiggy.search(foodName5);
System.out.println("Price of foodName is " +priceOfFoodName5);
String foodName6 = "VegNoodels";
double priceOfFoodName6=Swiggy.search(foodName6);
System.out.println("Price of foodName is " +priceOfFoodName6);
String foodName7 = "Garlicloaf";
double priceOfFoodName7=Swiggy.search(foodName7);
System.out.println("Price of foodName is " +priceOfFoodName7);
String foodName8 = "Wheatjumbo";
double priceOfFoodName8=Swiggy.search(foodName8);
System.out.println("Price of foodName is " +priceOfFoodName8);
String foodName9 = "BlackForest";
double priceOfFoodName9=Swiggy.search(foodName9);
System.out.println("Price of foodName is " +priceOfFoodName9);
String foodName10 = "Pineapple 1 lb";
double priceOfFoodName10=Swiggy.search(foodName10);
System.out.println("Price of foodName is " +priceOfFoodName10);
String foodName11 = "Pasta";
double priceOfFoodName11=Swiggy.search(foodName11);
System.out.println("Price of foodName is " +priceOfFoodName11);
String foodName12 = "DhalMakhani";
double priceOfFoodName12=Swiggy.search(foodName12);
System.out.println("Price of foodName is " +priceOfFoodName12);
String foodName13 = "Dalfry";
double priceOfFoodName13=Swiggy.search(foodName13);
System.out.println("Price of foodName is " +priceOfFoodName13);
String foodName14 = "PaneerButterMasala";
double priceOfFoodName14=Swiggy.search(foodName14);
System.out.println("Price of foodName is " +priceOfFoodName14);
String foodName15 = "Kadhaipaneer";
double priceOfFoodName15=Swiggy.search(foodName15);
System.out.println("Price of foodName is " +priceOfFoodName15);
String foodName16 = "JeeraRice";
double priceOfFoodName16=Swiggy.search(foodName16);
System.out.println("Price of foodName is " +priceOfFoodName16);
String foodName17 = "TawaRoti";
double priceOfFoodName17=Swiggy.search(foodName17);
System.out.println("Price of foodName is " +priceOfFoodName17);
String foodName18 = "Mixsauce";
double priceOfFoodName18=Swiggy.search(foodName18);
System.out.println("Price of foodName is " +priceOfFoodName18);
String foodName19 = "ButterKulcha";
double priceOfFoodName19=Swiggy.search(foodName19);
System.out.println("Price of foodName is " +priceOfFoodName19);
String foodName20 = "EggFry";
double priceOfFoodName20=Swiggy.search(foodName20);
System.out.println("Price of foodName is " +priceOfFoodName20);
}
}