class Swiggy1Tester{
public static void main(String args[]){
String foodName = "FriedRice";
double priceOfFoodName=Swiggy1.search(foodName);
System.out.println("Price of foodName is " +priceOfFoodName);
double priceWithQuantity=Swiggy1.search("FriedRice",2);
System.out.println("The Food Price With Quantity is " +priceWithQuantity);
String foodName1 = "VadaPav";
double priceOfFoodName1=Swiggy1.search(foodName1);
System.out.println("Price of foodName is " +priceOfFoodName1);
double priceWithQuantity1=Swiggy1.search("VadaPav",7);
System.out.println("The Food Price With Quantity is " +priceWithQuantity1);
String foodName2 = "CheeseGarlic";
double priceOfFoodName2=Swiggy1.search(foodName2);
System.out.println("Price of foodName is " +priceOfFoodName2);
double priceWithQuantity2=Swiggy1.search("CheeseGarlic",3);
System.out.println("The Food Price With Quantity is " +priceWithQuantity2);
String foodName3 = "CheeseCorn";
double priceOfFoodName3=Swiggy1.search(foodName3);
System.out.println("Price of foodName is " +priceOfFoodName3);
double priceWithQuantity3=Swiggy1.search("CheeseCorn",9);
System.out.println("The Food Price With Quantity is " +priceWithQuantity3);
String foodName4 = "PavBajji";
double priceOfFoodName4=Swiggy1.search(foodName4);
System.out.println("Price of foodName is " +priceOfFoodName4);
double priceWithQuantity4=Swiggy1.search("PavBajji",4);
System.out.println("The Food Price With Quantity is " +priceWithQuantity4);
String foodName5 = "PaneerTikka";
double priceOfFoodName5=Swiggy1.search(foodName5);
System.out.println("Price of foodName is " +priceOfFoodName5);
double priceWithQuantity5=Swiggy1.search("PaneerTikka",8);
System.out.println("The Food Price With Quantity is " +priceWithQuantity5);
String foodName6 = "VegNoodels";
double priceOfFoodName6=Swiggy1.search(foodName6);
System.out.println("Price of foodName is " +priceOfFoodName6);
double priceWithQuantity6=Swiggy1.search("VegNoodels",3);
System.out.println("The Food Price With Quantity is " +priceWithQuantity6);
String foodName7 = "Garlicloaf";
double priceOfFoodName7=Swiggy1.search(foodName7);
System.out.println("Price of foodName is " +priceOfFoodName7);
double priceWithQuantity7=Swiggy1.search("Garlicloaf",8);
System.out.println("The Food Price With Quantity is " +priceWithQuantity7);
String foodName8 = "Wheatjumbo";
double priceOfFoodName8=Swiggy1.search(foodName8);
System.out.println("Price of foodName is " +priceOfFoodName8);
double priceWithQuantity8=Swiggy1.search("Wheatjumbo",8);
System.out.println("The Food Price With Quantity is " +priceWithQuantity8);
String foodName9 = "BlackForest";
double priceOfFoodName9=Swiggy1.search(foodName9);
System.out.println("Price of foodName is " +priceOfFoodName9);
double priceWithQuantity9=Swiggy1.search("BlackForest",8);
System.out.println("The Food Price With Quantity is " +priceWithQuantity9);
String foodName10 = "Pineapple 1 lb";
double priceOfFoodName10=Swiggy1.search(foodName10);
System.out.println("Price of foodName is " +priceOfFoodName10);
double priceWithQuantity10=Swiggy1.search("Pineapple 1 1b",3);
System.out.println("The Food Price With Quantity is " +priceWithQuantity10);
String foodName11 = "Pasta";
double priceOfFoodName11=Swiggy1.search(foodName11);
System.out.println("Price of foodName is " +priceOfFoodName11);
double priceWithQuantity11=Swiggy1.search("Pasta",6);
System.out.println("The Food Price With Quantity is " +priceWithQuantity11);
String foodName12 = "DhalMakhani";
double priceOfFoodName12=Swiggy1.search(foodName12);
System.out.println("Price of foodName is " +priceOfFoodName12);
double priceWithQuantity12=Swiggy1.search("DhalMakhani",3);
System.out.println("The Food Price With Quantity is " +priceWithQuantity12);
String foodName13 = "Dalfry";
double priceOfFoodName13=Swiggy1.search(foodName13);
System.out.println("Price of foodName is " +priceOfFoodName13);
double priceWithQuantity13=Swiggy1.search("Dalfry",2);
System.out.println("The Food Price With Quantity is " +priceWithQuantity13);
String foodName14 = "PaneerButterMasala";
double priceOfFoodName14=Swiggy1.search(foodName14);
System.out.println("Price of foodName is " +priceOfFoodName14);
double priceWithQuantity14=Swiggy1.search("PaneerButterMasala",4);
System.out.println("The Food Price With Quantity is " +priceWithQuantity14);
String foodName15 = "Kadhaipaneer";
double priceOfFoodName15=Swiggy1.search(foodName15);
System.out.println("Price of foodName is " +priceOfFoodName15);
double priceWithQuantity15=Swiggy1.search("Kadhaipaneer",8);
System.out.println("The Food Price With Quantity is " +priceWithQuantity15);
String foodName16 = "JeeraRice";
double priceOfFoodName16=Swiggy1.search(foodName16);
System.out.println("Price of foodName is " +priceOfFoodName16);
double priceWithQuantity16=Swiggy1.search("JeeraRice",7);
System.out.println("The Food Price With Quantity is " +priceWithQuantity16);
String foodName17 = "TawaRoti";
double priceOfFoodName17=Swiggy1.search(foodName17);
System.out.println("Price of foodName is " +priceOfFoodName17);
double priceWithQuantity17=Swiggy1.search("TawaRoti",5);
System.out.println("The Food Price With Quantity is " +priceWithQuantity17);
String foodName18 = "Mixsauce";
double priceOfFoodName18=Swiggy1.search(foodName18);
System.out.println("Price of foodName is " +priceOfFoodName18);
double priceWithQuantity18=Swiggy1.search("Mixsauce",3);
System.out.println("The Food Price With Quantity is " +priceWithQuantity18);
String foodName19 = "ButterKulcha";
double priceOfFoodName19=Swiggy1.search(foodName19);
System.out.println("Price of foodName is " +priceOfFoodName19);
double priceWithQuantity19=Swiggy1.search("ButterKulcha",9);
System.out.println("The Food Price With Quantity is " +priceWithQuantity19);
String foodName20 = "EggFry";
double priceOfFoodName20=Swiggy1.search(foodName20);
System.out.println("Price of foodName is " +priceOfFoodName20);
double priceWithQuantity20=Swiggy1.search("EggFry",2);
System.out.println("The Food Price With Quantity is " +priceWithQuantity20);
}
}