class UbberEatsTester{
public static void main(String args[]){
String foodName = "LemonRice";
double priceOfFoodName=UbberEats.search(foodName);
System.out.println("Price of foodName is " +priceOfFoodName);
String foodName1 = "Pullihogre";
double priceOfFoodName1=UbberEats.search(foodName1);
System.out.println("Price of foodName is " +priceOfFoodName1);
String foodName2 = "SetDose";
double priceOfFoodName2=UbberEats.search(foodName2);
System.out.println("Price of foodName is " +priceOfFoodName2);
String foodName3 = "OnionDosa";
double priceOfFoodName3=UbberEats.search(foodName3);
System.out.println("Price of foodName is " +priceOfFoodName3);
String foodName4 = "Palav";
double priceOfFoodName4=UbberEats.search(foodName4);
System.out.println("Price of foodName is " +priceOfFoodName4);
String foodName5 = "Bisibelebath";
double priceOfFoodName5=UbberEats.search(foodName5);
System.out.println("Price of foodName is " +priceOfFoodName5);
String foodName6 = "Pakoda";
double priceOfFoodName6=UbberEats.search(foodName6);
System.out.println("Price of foodName is " +priceOfFoodName6);
String foodName7 = "Bajji";
double priceOfFoodName7=UbberEats.search(foodName7);
System.out.println("Price of foodName is " +priceOfFoodName7);
String foodName8 = "GeeRice";
double priceOfFoodName8=UbberEats.search(foodName8);
System.out.println("Price of foodName is " +priceOfFoodName8);
String foodName9 = "Kushka";
double priceOfFoodName9=UbberEats.search(foodName9);
System.out.println("Price of foodName is " +priceOfFoodName9);
String foodName10 = "Puri";
double priceOfFoodName10=UbberEats.search(foodName10);
System.out.println("Price of foodName is " +priceOfFoodName10);
String foodName11 = "Idli";
double priceOfFoodName11=UbberEats.search(foodName11);
System.out.println("Price of foodName is " +priceOfFoodName11);
String foodName12 = "Roti";
double priceOfFoodName12=UbberEats.search(foodName12);
System.out.println("Price of foodName is " +priceOfFoodName12);
String foodName13 = "Butterkulcha";
double priceOfFoodName13=UbberEats.search(foodName13);
System.out.println("Price of foodName is " +priceOfFoodName13);
String foodName14 = "Kulcha";
double priceOfFoodName14=UbberEats.search(foodName14);
System.out.println("Price of foodName is " +priceOfFoodName14);
String foodName15 = "Chapathi";
double priceOfFoodName15=UbberEats.search(foodName15);
System.out.println("Price of foodName is " +priceOfFoodName15);
String foodName16 = "DamBiryani";
double priceOfFoodName16=UbberEats.search(foodName16);
System.out.println("Price of foodName is " +priceOfFoodName16);
String foodName17 = "FriedRice";
double priceOfFoodName17=UbberEats.search(foodName17);
System.out.println("Price of foodName is " +priceOfFoodName17);
String foodName18 = "TomatoBath";
double priceOfFoodName18=UbberEats.search(foodName18);
System.out.println("Price of foodName is " +priceOfFoodName18);
String foodName19 = "JeeraRice";
double priceOfFoodName19=UbberEats.search(foodName19);
System.out.println("Price of foodName is " +priceOfFoodName19);
String foodName20 = "Maggi";
double priceOfFoodName20=UbberEats.search(foodName20);
System.out.println("Price of foodName is " +priceOfFoodName20);
}
}