class ZomatoTester{
public static void main(String args[]){
String foodName = "Pizza";
double priceOfFoodName=Zomato.search(foodName);
System.out.println("Price of foodName is " +priceOfFoodName);
String foodName1 = "Biryani";
double priceOfFoodName1=Zomato.search(foodName1);
System.out.println("Price of foodName is " +priceOfFoodName1);
String foodName2 = "Burger";
double priceOfFoodName2=Zomato.search(foodName2);
System.out.println("Price of foodName is " +priceOfFoodName2);
String foodName3 = "Sandwiche";
double priceOfFoodName3=Zomato.search(foodName3);
System.out.println("Price of foodName is " +priceOfFoodName3);
String foodName4 = "Kabab";
double priceOfFoodName4=Zomato.search(foodName4);
System.out.println("Price of foodName is " +priceOfFoodName4);
String foodName5 = "Shavarma";
double priceOfFoodName5=Zomato.search(foodName5);
System.out.println("Price of foodName is " +priceOfFoodName5);
String foodName6 = "Noodles";
double priceOfFoodName6=Zomato.search(foodName6);
System.out.println("Price of foodName is " +priceOfFoodName6);
String foodName7 = "Cake";
double priceOfFoodName7=Zomato.search(foodName7);
System.out.println("Price of foodName is " +priceOfFoodName7);
String foodName8 = "Chickenlolipop";
double priceOfFoodName8=Zomato.search(foodName8);
System.out.println("Price of foodName is " +priceOfFoodName8);
String foodName9 = "KFC";
double priceOfFoodName9=Zomato.search(foodName9);
System.out.println("Price of foodName is " +priceOfFoodName9);
String foodName10 = "VegPalav";
double priceOfFoodName10=Zomato.search(foodName10);
System.out.println("Price of foodName is " +priceOfFoodName10);
String foodName11 = "ChillyChicken";
double priceOfFoodName11=Zomato.search(foodName11);
System.out.println("Price of foodName is " +priceOfFoodName11);
String foodName12 = "Chicken65";
double priceOfFoodName12=Zomato.search(foodName12);
System.out.println("Price of foodName is " +priceOfFoodName12);
String foodName13 = "MasalaDosa";
double priceOfFoodName13=Zomato.search(foodName13);
System.out.println("Price of foodName is " +priceOfFoodName13);
String foodName14 = "Parota";
double priceOfFoodName14=Zomato.search(foodName14);
System.out.println("Price of foodName is " +priceOfFoodName14);
String foodName15 = "ChickenButterMasala";
double priceOfFoodName15=Zomato.search(foodName15);
System.out.println("Price of foodName is " +priceOfFoodName15);
String foodName16 = "Chicken";
double priceOfFoodName16=Zomato.search(foodName16);
System.out.println("Price of foodName is " +priceOfFoodName16);
String foodName17 = "IceCream";
double priceOfFoodName17=Zomato.search(foodName17);
System.out.println("Price of foodName is " +priceOfFoodName17);
String foodName18 = "GobiManchuri";
double priceOfFoodName18=Zomato.search(foodName18);
System.out.println("Price of foodName is " +priceOfFoodName18);
String foodName19 = "PaniPuri";
double priceOfFoodName19=Zomato.search(foodName19);
System.out.println("Price of foodName is " +priceOfFoodName19);
String foodName20 = "BelPuri";
double priceOfFoodName20=Zomato.search(foodName20);
System.out.println("Price of foodName is " +priceOfFoodName20);
}
}